### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by hiromichinomata** [jemsbhai/comicvision#1]
Is it possible to add license to this project?
MIT, Apache, etc...

**Comment by ghost** [comment]
Hey Hiromichi, 

Unfortunately according to the rules of the [Microsoft Hackathon](https://azureai.devpost.com/forum_topics/33160-adding-description-deployment-details) we are unable to edit any part of this submission till after the judging period is complete, this includes adding a proper README with appropriate licencing. However, if you visit https://github.com/jomanovic/comicvision you will find a parallel version with the appropriate license. Sorry for the trouble, let me know if there is anything else I can do to help.

**Comment by hiromichinomata** [comment]
Thank you for clear explanation. I've understood the regulation.
I will check the alternative one.

I tried the [similar thing](https://ja.algonote.com/entry/blackjack-ocr) before using GCP API and wanted to compare...
